"""Voice-to-ROS command router with a local parser and guarded motion output."""

import json
import math
import os
import pathlib
import sys
import time
import uuid

import rclpy
from geometry_msgs.msg import TwistStamped
from nav_msgs.msg import Odometry
from rclpy.node import Node
from rclpy.clock import Clock, ClockType
from std_msgs.msg import Bool, Float32, String
from std_srvs.srv import Trigger
from rclpy.qos import DurabilityPolicy, QoSProfile, ReliabilityPolicy

# Prefer the interfaces generated by the active ROSCAR workspace over an
# older vendor overlay that may be prepended by ros2 launch on Jetson.
_ws = pathlib.Path(os.environ.get('ROSCAR_WS', '/home/wheeltec/ROSCAR-current/ros2_ws'))
_iface = _ws.parent / 'install' / 'roscar_interfaces' / 'local' / 'lib' / 'python3.10' / 'dist-packages'
if _iface.is_dir():
    sys.path.insert(0, str(_iface))

from person_interfaces.msg import TargetState
from roscar_interfaces.msg import VoiceCommand, VoiceCommandResult
from roscar_interfaces.srv import SetControlMode

from .validation import (CommandValidationError, parse_local_text,
                         validate_drive, validate_mode)


class VoiceCommandRouter(Node):
    """Own the voice control state machine, never the final /cmd_vel topic."""

    def __init__(self, **kwargs):
        super().__init__('voice_command_router', **kwargs)
        self.declare_parameter('enabled', True)
        self.declare_parameter('local_parser_enabled', True)
        self.declare_parameter('input_topic', '/voice/asr_text')
        self.declare_parameter('command_topic', '/voice/command')
        self.declare_parameter('result_topic', '/voice/command_result')
        self.declare_parameter('control_request_topic', '/chassis/cmd_vel')
        self.declare_parameter('control_timeout_s', 2.0)
        self.declare_parameter('default_forward_mps', 0.08)
        self.declare_parameter('default_reverse_mps', -0.08)
        self.declare_parameter('default_turn_rps', 0.25)
        self.declare_parameter('default_duration_s', 2.0)
        self.declare_parameter('base_frame', 'base_link')
        self.declare_parameter('continuous_wake_text', '小车唤醒')
        self.declare_parameter('session_timeout_s', 30.0)
        self.declare_parameter('legacy_listen_polling', False)

        get = lambda key: self.get_parameter(key).value
        self._result_pub = self.create_publisher(VoiceCommandResult, get('result_topic'), 10)
        self._legacy_result_pub = self.create_publisher(String, '/voice/tool_result', 10)
        self._answer_pub = self.create_publisher(String, '/voice/assistant_text', 10)
        self._tts_pub = self.create_publisher(String, '/voice/tts_text', 10)
        session_qos = QoSProfile(depth=1, reliability=ReliabilityPolicy.RELIABLE,
                                 durability=DurabilityPolicy.TRANSIENT_LOCAL)
        self._session_pub = self.create_publisher(Bool, '/voice/session_active', session_qos)
        self._velocity_pub = self.create_publisher(TwistStamped, get('control_request_topic'), 1)

        self._set_mode = self.create_client(SetControlMode, '/control/set_mode')
        self._arm = self.create_client(Trigger, '/control/arm')
        self._stop = self.create_client(Trigger, '/control/stop')
        self._disarm = self.create_client(Trigger, '/control/disarm')

        self._state = {}
        self._state_at = 0.0
        self._generation = 0
        self._pending_arm = None
        self._pending_drive = None
        self._awaiting_arm_state = None
        self._seen = {}
        self._power = None
        self._odom = None
        self._target = None
        self._authorized = False
        self._mode_request = 'IDLE'
        self._velocity = (0.0, 0.0)
        self._last_drive = 0.0
        self._drive_until = 0.0
        self._stop_requested = False
        self._continuous_session = False
        self._session_deadline = 0.0
        self._listen_client = self.create_client(Trigger, '/voice/start_listening')
        self._next_listen_at = 0.0
        self._last_listen_attempt = 0.0

        self.create_subscription(String, get('input_topic'), self._on_asr, 10)
        self.create_subscription(String, '/voice_words', self._on_wake, 10)
        self.create_subscription(String, '/voice/asr_state', self._on_asr_state, 10)
        self.create_subscription(VoiceCommand, get('command_topic'), self._on_command, 10)
        self.create_subscription(String, '/control/state', self._on_state, 10)
        self.create_subscription(Float32, '/PowerVoltage', lambda msg: setattr(self, '_power', msg.data), 10)
        self.create_subscription(Odometry, '/odom', lambda msg: setattr(self, '_odom', msg), 2)
        self.create_subscription(TargetState, '/perception/target_state',
                                 lambda msg: setattr(self, '_target', msg), 10)
        self.create_timer(0.05, self._tick, clock=Clock(clock_type=ClockType.STEADY_TIME))
        self._session_pub.publish(Bool(data=False))

    def _legacy_polling(self):
        return str(self.get_parameter('legacy_listen_polling').value).lower() in ('true', '1')

    def _new_command(self, action, **kwargs):
        command = VoiceCommand()
        command.stamp = self.get_clock().now().to_msg()
        command.request_id = str(kwargs.get('request_id', 'local-' + str(uuid.uuid4())))
        command.action = action
        command.mode = str(kwargs.get('mode', ''))
        command.linear_mps = float(kwargs.get('linear_mps', 0.0))
        command.angular_rps = float(kwargs.get('angular_rps', 0.0))
        command.duration_s = float(kwargs.get('duration_s', 0.0))
        command.query = str(kwargs.get('query', ''))
        return command

    def _on_wake(self, message):
        trigger = str(self.get_parameter('continuous_wake_text').value).strip()
        if str(message.data).strip() != trigger:
            return
        was_active = self._continuous_session
        self._continuous_session = True
        self._session_deadline = time.monotonic() + float(
            self.get_parameter('session_timeout_s').value)
        self._session_pub.publish(Bool(data=True))
        if not was_active:
            self._speak('我在')
            self.get_logger().info('语音控制会话已开启')
        else:
            self.get_logger().info('语音控制会话已刷新')

    def _end_session(self, command=None):
        self._continuous_session = False
        self._session_deadline = 0.0
        self._next_listen_at = 0.0
        self._last_listen_attempt = 0.0
        self._session_pub.publish(Bool(data=False))
        if command is not None or self._authorized or self._mode_request != 'IDLE':
            self._stop_motion(command or self._new_command(
                'DISARM', request_id='session-expired-' + str(uuid.uuid4())), set_idle=True)
        self.get_logger().info('语音控制会话已结束')

    def _on_asr_state(self, message):
        state = str(message.data).strip()
        if self._continuous_session and (state == 'OVERLOAD' or state.startswith('ERROR:')):
            self._end_session()
            return
        if self._continuous_session and state == 'RECOGNIZING':
            self._session_deadline = time.monotonic() + float(
                self.get_parameter('session_timeout_s').value)
        # The old Xfyun and offline entry points still recognize one turn at a time.
        if self._legacy_polling() and self._continuous_session and state == 'IDLE':
            self._request_next_listen()

    def _request_next_listen(self):
        if self._continuous_session and self._legacy_polling():
            # ASR publishes the result just before it clears its busy flag;
            # defer the service call so the next request is not rejected as busy.
            self._next_listen_at = max(self._next_listen_at, time.monotonic() + 0.35)


    def _on_asr(self, message):
        text = str(message.data).strip()
        if not self._continuous_session:
            self.get_logger().warning(f'忽略会话外 ASR 文本: {text!r}')
            return
        if time.monotonic() >= self._session_deadline:
            self._end_session()
            self.get_logger().warning(f'忽略过期会话中的 ASR 文本: {text!r}')
            return
        self._session_deadline = time.monotonic() + float(
            self.get_parameter('session_timeout_s').value)
        if not self.get_parameter('local_parser_enabled').value:
            self.get_logger().warning('本地语音规则已关闭，拒绝执行指令')
            self._speak('语音控制规则已关闭')
            self._request_next_listen()
            return
        try:
            parsed = parse_local_text(
                text,
                forward_mps=float(self.get_parameter('default_forward_mps').value),
                reverse_mps=float(self.get_parameter('default_reverse_mps').value),
                turn_rps=float(self.get_parameter('default_turn_rps').value),
                duration_s=float(self.get_parameter('default_duration_s').value),
            )
        except CommandValidationError as exc:
            self.get_logger().info(f'忽略无法解析的语音文本: {text!r} ({exc})')
            self._request_next_listen()
            return
        if parsed is None:
            self.get_logger().info(f'忽略未匹配指令的语音文本: {text!r}')
            self._request_next_listen()
            return
        self.get_logger().info(f'语音文本: {text!r} -> 本地动作: {parsed}')
        command = self._new_command(**parsed)
        if command.action == 'DISARM':
            self._end_session(command)
        else:
            self._on_command(command)
        self._request_next_listen()

    def _on_command(self, command):
        try:
            action = command.action
            if action not in ('STOP', 'DISARM'):
                if not self.get_parameter('enabled').value:
                    raise CommandValidationError('语音控制已关闭')
                stamp = command.stamp.sec + command.stamp.nanosec * 1e-9
                age = self.get_clock().now().nanoseconds * 1e-9 - stamp
                if stamp <= 0 or not 0 <= age <= 2.0:
                    raise CommandValidationError('命令已过期或时间戳无效')
            now = time.monotonic()
            self._seen = {k:v for k,v in self._seen.items() if now-v < 60}
            if not command.request_id or command.request_id in self._seen:
                raise CommandValidationError('命令标识无效或重复')
            self._seen[command.request_id] = now
            if action == 'DRIVE':
                self._drive_or_arm(
                    validate_drive(command.linear_mps, command.angular_rps, command.duration_s),
                    command)
            elif action == 'SET_MODE':
                self._set_control_mode(validate_mode(command.mode), command)
            elif action == 'ARM':
                self._set_control_mode('EXTERNAL', command)
            elif action in ('STOP', 'DISARM'):
                self._stop_motion(command, set_idle=True)
            elif action == 'QUERY_STATUS':
                self._query_status(command)
            else:
                raise CommandValidationError(f'未知语音动作: {action}')
        except (CommandValidationError, ValueError) as exc:
            self._publish_result(command, False, str(exc))

    def _drive_or_arm(self, drive, command):
        if self._authorized and self._mode_request == 'EXTERNAL':
            self._drive(drive, command)
        elif command.request_id.startswith('local-') and self._continuous_session:
            self._set_control_mode('EXTERNAL', command, pending_drive=drive)
        else:
            self._publish_result(command, False, '请先完成手动模式授权')

    def _drive(self, drive, command):
        if not self._authorized or self._mode_request != 'EXTERNAL':
            self._publish_result(command, False, '手动模式尚未授权')
            return
        self._velocity = (drive.linear_mps, drive.angular_rps)
        self._last_drive = time.monotonic()
        self._drive_until = self._last_drive + drive.duration_s
        self._stop_requested = False
        self._publish_result(command, True, f'已接受速度请求 {drive.linear_mps:.2f} m/s、角速度 {drive.angular_rps:.2f} rad/s')

    def _set_control_mode(self, mode, command, pending_drive=None):
        self._generation += 1
        self._pending_arm = None
        self._awaiting_arm_state = None
        self._pending_drive = (pending_drive, command, self._generation) if pending_drive else None
        self._mode_request = mode
        self._authorized = False
        self._velocity = (0.0, 0.0)
        if mode == 'IDLE':
            self._stop_motion(command, set_idle=True)
            return
        if not self._set_mode.service_is_ready():
            self._publish_result(command, False, '控制模式服务不可用')
            return
        request = SetControlMode.Request(); request.mode = mode
        future = self._set_mode.call_async(request)
        generation = self._generation
        future.add_done_callback(lambda f: self._mode_done(f, command, mode, generation))

    def _mode_done(self, future, command, mode, generation):
        if generation != self._generation:
            return
        try:
            response = future.result()
            if not response.success:
                self._publish_result(command, False, response.message)
                return
            self._pending_arm = (command, mode, generation, time.monotonic()+3.0)
        except Exception as exc:
            self._publish_result(command, False, f'模式切换失败: {exc}')

    def _arm_done(self, command, response):
        if not response.success:
            self._authorized = False
            self._publish_result(command, False, response.message or '授权失败')
            return
        pending = self._pending_drive
        self._pending_drive = None
        drive = pending[0] if pending and pending[2] == self._generation else None
        # The service response can precede /control/state.  Do not publish
        # velocity until the guard itself reports ARMED for this mode.
        self._awaiting_arm_state = (command, drive, self._generation,
                                    time.monotonic() + 1.5)

    def _call_trigger(self, client, command, label, after=None):
        if not client.service_is_ready():
            self._publish_result(command, False, f'{label}服务不可用')
            return
        generation = self._generation
        future = client.call_async(Trigger.Request())
        def done(f):
            if generation != self._generation:
                return
            try:
                result = f.result()
                if after:
                    after(command, result)
                else:
                    self._publish_result(command, bool(result.success), result.message or label)
            except Exception as exc:
                self._publish_result(command, False, f'{label}失败: {exc}')
        future.add_done_callback(done)

    def _stop_motion(self, command, set_idle=False):
        self._generation += 1
        self._pending_arm = None
        self._pending_drive = None
        self._awaiting_arm_state = None
        self._authorized = False
        self._velocity = (0.0, 0.0)
        self._drive_until = 0.0
        self._stop_requested = True
        self._mode_request = 'IDLE' if set_idle else self._mode_request
        client = self._disarm if command.action == 'DISARM' else self._stop
        label = '撤销授权' if command.action == 'DISARM' else '停止'
        self._call_trigger(client, command, label, self._stop_done)

    def _stop_done(self, command, response):
        if not response.success:
            self._publish_result(command, False, response.message or '停止失败')
            return
        if command.action in ('STOP', 'DISARM') and self._set_mode.service_is_ready():
            request = SetControlMode.Request(); request.mode = 'IDLE'
            future = self._set_mode.call_async(request)
            def mode_done(f):
                try:
                    result = f.result()
                    self._publish_result(command, bool(result.success),
                                         ('已停止并退出控制' if command.action == 'DISARM'
                                          else '已停止') if result.success else result.message)
                except Exception as exc:
                    self._publish_result(command, False, f'退出遥控失败: {exc}')
            future.add_done_callback(mode_done)
        else:
            self._publish_result(command, True, response.message or '已停止')

    def _query_status(self, command):
        if command.query == 'unsupported_navigation':
            self._publish_result(command, False, '当前未接入导航目标和地点映射')
            return
        state = self._state
        parts = [f"模式 {state.get('command_mode', self._mode_request)}",
                 f"保护状态 {state.get('mode', '未知')}"]
        if self._power is not None and math.isfinite(float(self._power)):
            parts.append(f'电量 {self._power:.2f} V')
        if self._target is not None:
            parts.append('已锁定目标' if self._target.status == TargetState.TRACKING else '当前没有有效跟随目标')
        self._publish_result(command, True, '，'.join(parts))

    def _on_state(self, message):
        try:
            value = json.loads(message.data)
            if isinstance(value, dict):
                self._state = value
                self._state_at = time.monotonic()
        except (TypeError, ValueError):
            self.get_logger().warning('忽略格式错误的 /control/state')

    def _tick(self):
        now = time.monotonic()
        if self._continuous_session and now >= self._session_deadline:
            self._end_session()
        if self._legacy_polling() and self._continuous_session and self._listen_client.service_is_ready():
            due = self._next_listen_at and now >= self._next_listen_at
            keepalive = now - self._last_listen_attempt >= 1.0
            if due or keepalive:
                self._next_listen_at = 0.0
                self._last_listen_attempt = now
                self._listen_client.call_async(Trigger.Request())
        if self._pending_arm:
            command, mode, generation, deadline = self._pending_arm
            if now > deadline:
                self._pending_arm = None
                self._publish_result(command, False, '等待新鲜控制请求超时')
            elif (now-self._state_at < .3 and self._state.get('command_mode') == mode
                  and self._state.get('ready')):
                self._pending_arm = None
                self._call_trigger(self._arm, command, '模式授权', self._arm_done)
        if self._awaiting_arm_state:
            command, drive, generation, deadline = self._awaiting_arm_state
            if generation != self._generation:
                self._awaiting_arm_state = None
            elif (now - self._state_at < .3 and
                  self._state.get('command_mode') == self._mode_request and
                  self._state.get('mode') == 'ARMED'):
                self._awaiting_arm_state = None
                self._authorized = True
                self._last_drive = self._drive_until = 0.0
                self._stop_requested = False
                if drive is not None:
                    self._drive(drive, command)
                else:
                    self._publish_result(command, True, '已授权，可以发出运动指令')
            elif now >= deadline:
                self._awaiting_arm_state = None
                self._stop_motion(self._new_command(
                    'DISARM', request_id='arm-unconfirmed-' + str(uuid.uuid4())),
                    set_idle=True)
                self._publish_result(command, False, '控制器未确认已授权，未执行运动')
        # A delayed state update must not revoke a valid authorization.  The
        # controller itself keeps publishing its state; only an explicit
        # non-armed/non-external state should invalidate this session.
        if self._authorized and self._state and (
                self._state.get('mode') != 'ARMED' or
                self._state.get('command_mode') != self._mode_request):
            self._stop_motion(self._new_command('STOP', request_id='internal-' + str(uuid.uuid4())), set_idle=True)
        if self._authorized and self._mode_request == 'EXTERNAL':
            drive_expired = self._drive_until > 0.0 and now > self._drive_until
            command_expired = (
                self._last_drive > 0.0
                and now - self._last_drive > float(self.get_parameter('control_timeout_s').value)
            )
            if drive_expired or command_expired:
                self._velocity = (0.0, 0.0)
                # Motion timeout is a velocity timeout, not an authorization
                # timeout.  Keep EXTERNAL authorization so the next voice
                # command can run without requiring ARM again.
                self._drive_until = 0.0
                self._last_drive = 0.0
                self._stop_requested = False
        if self._mode_request != 'EXTERNAL':
            return
        msg = TwistStamped()
        msg.header.stamp = self.get_clock().now().to_msg()
        msg.header.frame_id = str(self.get_parameter('base_frame').value)
        if self._authorized and self._mode_request == 'EXTERNAL':
            msg.twist.linear.x, msg.twist.angular.z = self._velocity
        self._velocity_pub.publish(msg)

    def _publish_result(self, command, success, message):
        result = VoiceCommandResult()
        result.stamp = self.get_clock().now().to_msg()
        result.request_id = command.request_id
        result.action = command.action
        result.success = bool(success)
        result.message = str(message)
        result.command_mode = self._state.get('command_mode', self._mode_request)
        result.guard_mode = self._state.get('mode', '')
        self._result_pub.publish(result)
        self._legacy_result_pub.publish(String(data=json.dumps({
            'request_id': result.request_id, 'success': result.success,
            'detail': result.message,
        }, ensure_ascii=False)))
        self.get_logger().info(
            f'控制结果: action={result.action} success={result.success} '
            f'mode={result.command_mode} guard={result.guard_mode} detail={result.message}')
        if result.request_id.startswith(('local-', 'legacy-')):
            if result.action != 'DRIVE' or not result.success:
                self._speak('已停止' if result.action == 'STOP' and result.success
                            else result.message)

    def _speak(self, text):
        message = String(data=str(text))
        self._answer_pub.publish(message)
        self._tts_pub.publish(message)


def main(args=None):
    rclpy.init(args=args)
    node = VoiceCommandRouter()
    try:
        rclpy.spin(node)
    except KeyboardInterrupt:
        pass
    finally:
        node._velocity = (0.0, 0.0)
        node.destroy_node()
        if rclpy.ok():
            rclpy.shutdown()
