"""ROS 2 text bridge from ASR to DeepSeek and TTS."""

import os
import json
import pathlib
import queue
import re
import sys
import threading
import time
import uuid

import rclpy
from rclpy.node import Node
from std_msgs.msg import Bool, String

# Prefer the interfaces generated by the active ROSCAR workspace over an
# older vendor overlay that may be prepended by ros2 launch on Jetson.
_ws = pathlib.Path(os.environ.get('ROSCAR_WS', '/home/wheeltec/ROSCAR-current/ros2_ws'))
_iface = _ws.parent / 'install' / 'roscar_interfaces' / 'local' / 'lib' / 'python3.10' / 'dist-packages'
if _iface.is_dir():
    sys.path.insert(0, str(_iface))

from roscar_interfaces.msg import VoiceCommand, VoiceCommandResult

from .client import DeepSeekClient
from .response_log import append_response


_THINK_BLOCK = re.compile(r'<think>.*?</think>', re.DOTALL)


class DeepSeekChatNode(Node):
    def __init__(self):
        super().__init__('deepseek_chat')
        self.declare_parameter('base_url', 'https://api.deepseek.com')
        self.declare_parameter('model', 'deepseek-v4-flash')
        self.declare_parameter('thinking_enabled', False)
        self.declare_parameter('timeout_sec', 30.0)
        self.declare_parameter('max_tokens', 300)
        self.declare_parameter('history_turns', 6)
        self.declare_parameter(
            'system_prompt',
            '你是运行在室内 ROS 2 小车上的中文语音助手。回答简洁、口语化，'
            '不要使用 Markdown。涉及车辆动作时必须调用结构化工具，不能凭空声称动作已完成。'
            '只允许在用户明确要求时调用运动、模式、状态或蜂鸣器工具。',
        )
        self.declare_parameter('input_topic', '/voice/unhandled_text')
        self.declare_parameter('answer_topic', '/voice/assistant_text')
        self.declare_parameter('tts_topic', '/voice/tts_text')
        self.declare_parameter('tool_call_topic', '/voice/tool_call')
        self.declare_parameter('command_topic', '/voice/command')
        self.declare_parameter('command_result_topic', '/voice/command_result')
        self.declare_parameter('response_log_path', '')
        self.declare_parameter('enable_tools', True)
        self.declare_parameter('wake_reply_enabled', True)
        self.declare_parameter('wake_reply_topic', '/voice_words')
        self.declare_parameter('wake_reply_trigger', '小车唤醒')
        self.declare_parameter('wake_reply_text', '我在')
        self.declare_parameter(
            'ignored_phrases',
            ['小车唤醒', '你好小微', '小微小微', '你好小薇', '小薇小薇'],
        )

        self._answer_pub = self.create_publisher(
            String, self.get_parameter('answer_topic').value, 10)
        self._tts_pub = self.create_publisher(
            String, self.get_parameter('tts_topic').value, 10)
        self._tts_speaking = False
        self._speaking_sub = self.create_subscription(
            Bool, '/voice/speaking', self._on_speaking, 10)
        self._wake_sub = None
        wake_topic = str(self.get_parameter('wake_reply_topic').value)
        if bool(self.get_parameter('wake_reply_enabled').value) and wake_topic:
            self._wake_sub = self.create_subscription(
                String, wake_topic, self._on_wake, 10)
        self._tool_pub = self.create_publisher(
            VoiceCommand, self.get_parameter('command_topic').value, 10)
        self._result_sub = self.create_subscription(
            VoiceCommandResult, self.get_parameter('command_result_topic').value,
            self._on_command_result, 10)
        self._state_pub = self.create_publisher(String, '/voice/chat_state', 10)
        self._subscription = self.create_subscription(
            String, self.get_parameter('input_topic').value, self._on_text, 10)

        self._ignored = set(self.get_parameter('ignored_phrases').value)
        self._system_prompt = self.get_parameter('system_prompt').value
        self._history = []
        self._queue = queue.Queue(maxsize=3)
        self._stop = threading.Event()
        self._result_events = {}
        self._result_values = {}
        self._worker = threading.Thread(target=self._worker_loop, daemon=True)
        self._worker.start()
        self._publish_state('IDLE')

    def _publish_state(self, value):
        message = String()
        message.data = value
        self._state_pub.publish(message)

    def _on_text(self, message):
        text = message.data.strip()
        if not text or text in self._ignored:
            return
        try:
            self._queue.put_nowait(text)
        except queue.Full:
            self.get_logger().warning('DeepSeek 请求队列已满，丢弃新问题')

    def _on_speaking(self, message):
        self._tts_speaking = bool(message.data)

    def _on_command_result(self, message):
        event = self._result_events.get(message.request_id)
        if event is None:
            return
        self._result_values[message.request_id] = message
        event.set()

    def _on_wake(self, message):
        trigger = str(self.get_parameter('wake_reply_trigger').value).strip()
        if message.data.strip() != trigger:
            return
        if self._tts_speaking:
            self.get_logger().info('TTS 正在播放，跳过唤醒应答')
            return
        reply = String()
        reply.data = str(self.get_parameter('wake_reply_text').value)
        self._tts_pub.publish(reply)
        self.get_logger().info(f'唤醒应答: {reply.data}')

    def _messages_for(self, user_text):
        return [
            {'role': 'system', 'content': self._system_prompt},
            *self._history,
            {'role': 'user', 'content': user_text},
        ]

    def _remember(self, user_text, answer):
        self._history.extend([
            {'role': 'user', 'content': user_text},
            {'role': 'assistant', 'content': answer},
        ])
        history_turns = max(0, int(self.get_parameter('history_turns').value))
        self._history = self._history[-2 * history_turns:] if history_turns else []

    def _client(self):
        api_key = os.environ.get('DEEPSEEK_API_KEY', '').strip()
        if not api_key:
            raise RuntimeError('未设置 DEEPSEEK_API_KEY')
        return DeepSeekClient(
            api_key,
            base_url=self.get_parameter('base_url').value,
            model=self.get_parameter('model').value,
            timeout_sec=float(self.get_parameter('timeout_sec').value),
            max_tokens=int(self.get_parameter('max_tokens').value),
            thinking_enabled=bool(self.get_parameter('thinking_enabled').value),
        )

    @staticmethod
    def _tools():
        def tool(name, description, properties, required=None):
            return {'type': 'function', 'function': {'name': name,
                'description': description, 'parameters': {
                    'type': 'object', 'properties': properties,
                    **({'required': required} if required else {}),
                    'additionalProperties': False}}}
        return [
            tool('drive', '按明确速度和时长控制底盘；不能替用户猜测数值。', {
                'linear_mps': {'type': 'number', 'minimum': -0.15, 'maximum': 0.15},
                'angular_rps': {'type': 'number', 'minimum': -0.5, 'maximum': 0.5},
                'duration_s': {'type': 'number', 'minimum': 0.05, 'maximum': 2.0},
            }, ['linear_mps', 'angular_rps', 'duration_s']),
            tool('set_control_mode', '切换 IDLE、EXTERNAL 或 FOLLOW 控制来源。', {
                'mode': {'type': 'string', 'enum': ['IDLE', 'EXTERNAL', 'FOLLOW']},
            }, ['mode']),
            tool('arm', '用户明确要求开始遥控或授权运动时调用。', {}),
            tool('stop', '用户要求停止或急停时调用。', {}),
            tool('query_status', '查询当前控制状态、电量和跟随目标状态。', {
                'query': {'type': 'string', 'enum': ['status', 'unsupported_navigation']},
            }, ['query']),
            tool('buzz', '用户明确要求蜂鸣器响时调用。', {
                'duration_ms': {'type': 'integer', 'minimum': 100, 'maximum': 2000},
            }, ['duration_ms']),
        ]

    def _handle_tool_calls(self, message):
        tool_calls = message.get('tool_calls') or []
        if len(tool_calls) != 1:
            raise RuntimeError('只允许一次调用一个机器人工具')
        function = tool_calls[0].get('function') or {}
        name = function.get('name')
        allowed = {'drive', 'set_control_mode', 'arm', 'stop', 'query_status', 'buzz'}
        if name not in allowed:
            raise RuntimeError(f'拒绝未知工具: {name}')
        try:
            arguments = json.loads(function.get('arguments') or '{}')
        except json.JSONDecodeError as exc:
            raise RuntimeError('工具参数不是有效 JSON') from exc
        schemas = {
            'drive': {'linear_mps', 'angular_rps', 'duration_s'},
            'set_control_mode': {'mode'},
            'arm': set(), 'stop': set(),
            'query_status': {'query'}, 'buzz': {'duration_ms'},
        }
        if not isinstance(arguments, dict) or set(arguments) != schemas[name]:
            raise RuntimeError(f'{name} 参数不完整或包含未知字段')
        command = VoiceCommand()
        command.stamp = self.get_clock().now().to_msg()
        command.request_id = str(uuid.uuid4())
        command.action = {'drive': 'DRIVE', 'set_control_mode': 'SET_MODE',
                          'arm': 'ARM', 'stop': 'STOP',
                          'query_status': 'QUERY_STATUS', 'buzz': 'BUZZ'}[name]
        if name == 'drive':
            command.linear_mps = float(arguments['linear_mps'])
            command.angular_rps = float(arguments['angular_rps'])
            command.duration_s = float(arguments['duration_s'])
        elif name == 'set_control_mode':
            command.mode = arguments['mode']
        elif name == 'query_status':
            command.query = arguments['query']
        elif name == 'buzz':
            command.duration_s = float(arguments['duration_ms']) / 1000.0
        event = threading.Event()
        self._result_events[command.request_id] = event
        self._tool_pub.publish(command)
        if not event.wait(timeout=5.0):
            self._result_events.pop(command.request_id, None)
            self._result_values.pop(command.request_id, None)
            raise RuntimeError('控制节点未在 5 秒内返回结果')
        result = self._result_values.pop(command.request_id)
        self._result_events.pop(command.request_id, None)
        if not result.success:
            raise RuntimeError(result.message)
        return result.message

    def _worker_loop(self):
        while not self._stop.is_set():
            try:
                user_text = self._queue.get(timeout=0.2)
            except queue.Empty:
                continue
            if user_text is None:
                break
            try:
                self._publish_state('THINKING')
                client = self._client()
                last_error = None
                for attempt in range(2):
                    try:
                        tools = self._tools() if bool(
                            self.get_parameter('enable_tools').value) else None
                        message = client.complete(
                            self._messages_for(user_text), tools=tools, tool_choice='auto')
                        break
                    except Exception as exc:
                        last_error = exc
                        if attempt == 0:
                            time.sleep(0.5)
                else:
                    raise last_error
                if message.get('tool_calls'):
                    answer = self._handle_tool_calls(message)
                else:
                    answer = message.get('content') or ''
                answer = _THINK_BLOCK.sub('', answer).strip()
                if not answer:
                    raise RuntimeError('移除思考标签后回答为空')
                self._remember(user_text, answer)
                response_log_path = str(
                    self.get_parameter('response_log_path').value).strip()
                if response_log_path:
                    try:
                        append_response(response_log_path, answer)
                    except OSError as exc:
                        self.get_logger().error(f'写入 DeepSeek 回答文件失败: {exc}')
                message = String()
                message.data = answer
                self._answer_pub.publish(message)
                self._tts_pub.publish(message)
                self.get_logger().info(f'回答: {answer}')
            except Exception as exc:
                self.get_logger().error(str(exc))
                self._publish_state(f'ERROR: {exc}')
            finally:
                if not self._stop.is_set():
                    self._publish_state('IDLE')
                self._queue.task_done()

    def destroy_node(self):
        self._stop.set()
        try:
            self._queue.put_nowait(None)
        except queue.Full:
            pass
        self._worker.join(timeout=2)
        return super().destroy_node()


def main(args=None):
    rclpy.init(args=args)
    node = DeepSeekChatNode()
    try:
        rclpy.spin(node)
    except KeyboardInterrupt:
        pass
    finally:
        node.destroy_node()
        if rclpy.ok():
            rclpy.shutdown()
